### ISSUE TITLE
add avnav path to oexserverdDirs

### ISSUE THREAD

**Issue by haklein** [hornang/oesenc-export#2]
When importing ocharts into AVNav the `oexserverd` is in a different location:
~~~
diff --git a/oesenc-export.py b/oesenc-export.py
index 1855116..e3a83f5 100755
--- a/oesenc-export.py
+++ b/oesenc-export.py
@@ -109,6 +109,7 @@ def locateService():
         oexserverdDirs = [os.path.expandvars('$HOME/.var/app/org.opencpn.OpenCPN/bin'),
                           os.path.expandvars('$HOME/.local/bin'),
                           '/usr/local/bin',
+                          '/usr/lib/avnav/plugins/ocharts/bin/',
                           '/usr/bin']
 
         for dir in oexserverdDirs:
~~~

**Comment by hornang** [comment]
@haklein I also added the directory used by the `ochartsng`. I suppose your directory related to the `ocharts-plugin`, but I wasn't able to verify that.

**Comment by haklein** [comment]
@hornang correct! Btw, do you have a pointer for the required change to use the exported maps in current opencpn versions?

**Comment by hornang** [comment]
@haklein You can apply this diff to [o-charts_pi](https://github.com/bdbcat/o-charts_pi/): https://gist.github.com/hornang/107ec4185f7e427afa545d65a6262768 And build the plugin so that it is compatible with OpenCPN (might need to build both projects). You can also fiddle in [pluginmanager.cpp](https://github.com/OpenCPN/OpenCPN/blob/master/gui/src/pluginmanager.cpp) to load the plugin from a alternative location.

**Comment by haklein** [comment]
thanks so much, that did very help!
